/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AvatarMenu: typeof import('./components/AvatarMenu.vue')['default']
    Coin: typeof import('./components/coin/Coin.vue')['default']
    CoinGroupModel: typeof import('./components/coin/CoinGroupModel.vue')['default']
    CoinModel: typeof import('./components/coin/CoinModel.vue')['default']
    CoinScene: typeof import('./components/coin/CoinScene.vue')['default']
    CTAForm: typeof import('./components/invest/CTAForm.vue')['default']
    FAQAccordion: typeof import('./components/invest/FAQAccordion.vue')['default']
    FinalCTA: typeof import('./components/invest/FinalCTA.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    HowItWorksSteps: typeof import('./components/invest/HowItWorksSteps.vue')['default']
    InvestHero: typeof import('./components/invest/InvestHero.vue')['default']
    InvestorProfile: typeof import('./components/invest/InvestorProfile.vue')['default']
    OnBoardingCard: typeof import('./components/cards/OnBoardingCard.vue')['default']
    OnBoardingCardGroup: typeof import('./components/cards/OnBoardingCardGroup.vue')['default']
    PriceSimulator: typeof import('./components/PriceSimulator.vue')['default']
    PriceSimulatorInline: typeof import('./components/PriceSimulatorInline.vue')['default']
    RoundSummaryCards: typeof import('./components/invest/RoundSummaryCards.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/SideBar.vue')['default']
    StickyMobileCTA: typeof import('./components/invest/StickyMobileCTA.vue')['default']
    StructureExplainer: typeof import('./components/invest/StructureExplainer.vue')['default']
    TrustStrip: typeof import('./components/invest/TrustStrip.vue')['default']
    WhatIsExury: typeof import('./components/invest/WhatIsExury.vue')['default']
    WhatYouReceive: typeof import('./components/invest/WhatYouReceive.vue')['default']
    WhyNow: typeof import('./components/invest/WhyNow.vue')['default']
  }
}
